<a href="https://colab.research.google.com/github/oxcracx/ml-learn/blob/main/LinearReg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Linear Regression multiple variable.

In [35]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [32]:
!pip install word2number

Collecting word2number
  Downloading word2number-1.1.zip (9.7 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: word2number
  Building wheel for word2number (setup.py) ... done
  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5568 sha256=d8cd7920e11c11d1ce6180388172beb89f248480f5282834afa16f5397f3ebf1
  Stored in directory: /root/.cache/pip/wheels/5b/79/fb/d25928e599c7e11fe4e00d32048cd74933f34a74c633d2aea6
Successfully built word2number
Installing collected packages: word2number
Successfully installed word2number-1.1

In [87]:
df = pd.read_csv("/content/hiring.csv")
df

  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [88]:
import math
median_test_score = math.floor(df['test_score(out of 10)'].mean())
median_test_score

7

In [89]:
import math
mean_test_score = math.floor(df['test_score(out of 10)'].mean())
df['test_score(out of 10)'] = df['test_score(out of 10)'].fillna(mean_test_score)
display(df)

  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    7.0                           7      72000
7     eleven                    7.0                           8      80000

In [90]:
reg = linear_model.LinearRegression()

In [91]:
from word2number import w2n
df['experience'] = df['experience'].apply(lambda x: w2n.word_to_num(x) if isinstance(x, str) else x)
df['experience'] = df['experience'].fillna(0)

reg.fit(df[['experience','test_score(out of 10)','interview_score(out of 10)']],df['salary($)'])

LinearRegression()

In [92]:
df

   experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         0.0                    8.0                           9      50000
1         0.0                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    7.0                           7      72000
7        11.0                    7.0                           8      80000

In [93]:
reg.coef_

array([2922.26901502, 2221.30909959, 2147.48256637])

In [94]:
reg.intercept_

np.float64(14992.65144669314)

In [98]:
import pandas as pd
new_candidate = pd.DataFrame([[2, 9, 6]], columns=['experience', 'test_score(out of 10)', 'interview_score(out of 10)'])
predicted_salary = reg.predict(new_candidate)
print(f"Predicted salary: ${predicted_salary[0]:.2f}")

Predicted salary: $53713.87

In [101]:
ew_candidate = pd.DataFrame([[12, 10, 10]], columns=['experience', 'test_score(out of 10)', 'interview_score(out of 10)'])
predicted_salary = reg.predict(new_candidate)
print(f"Predicted salary: ${predicted_salary[0]:.2f}")

Predicted salary: $53713.87

Ohhh brooooo, well to train this i read some documentains as well as used gemini, don't do blindly.